name: RSS → Repo (Substack sync)

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      import_latest_only:
        description: "Import only the latest Substack post"
        required: false
        default: "true"
        type: boolean
      debug:
        description: "Enable verbose debug output"
        required: false
        default: "false"
        type: boolean
  # Run hourly at :15 UTC
  schedule:
    - cron: "22 * * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Run sync
        env:
          # RAW feed (do not pre-wrap)
          SUBSTACK_RSS_URL: "https://hallowayfinch.substack.com/feed"
          # Your Cloudflare Worker proxy
          RSS_PROXY_URL: "https://rss.fincharchive.com"
          # New posts only by default; verbose logs off by default
          IMPORT_LATEST_ONLY: "1"
          IMPORT_DEBUG: ${{ inputs.debug == 'true' && '1' || '0' }}
        run: |
          set -euo pipefail
          echo "=== python version ==="; python --version
          echo "=== env ==="
          echo "RSS_PROXY_URL=${RSS_PROXY_URL}"
          echo "SUBSTACK_RSS_URL=${SUBSTACK_RSS_URL}"
          echo "IMPORT_LATEST_ONLY=${IMPORT_LATEST_ONLY}"
          echo "IMPORT_DEBUG=${IMPORT_DEBUG}"
          echo "=== running importer ==="
          python scripts/rss_to_repo.py
          echo "=== post-run tree ==="
          find . -maxdepth 2 -type d | sort
          echo "--- .finch ---"; ls -la .finch || true
          echo "--- _logs ---"; ls -la _logs || true
          echo "--- logs ---"; ls -la logs || true

      - name: Commit & push changes
        run: |
          git config user.name "Finch Bot"
          git config user.email "actions@github.com"
          git add _logs logs .finch/state.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(logs): import new Substack posts & rebuild pages"
            git push
          else
            echo "No new posts to commit."
          fi
