name: "RSS → Repo (Substack sync)"

on:
  workflow_dispatch:
    inputs:
      import_latest_only:
        description: "Import only the most recent post?"
        required: false
        default: "true"
      debug:
        description: "Verbose debug logging?"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install feedparser markdownify pyyaml requests

      - name: Run sync
        env:
          SUBSTACK_RSS_URL: "https://hallowayfinch.substack.com/feed"
          RSS_PROXY_URL: "https://rss.fincharchive.com"  # your working Cloudflare proxy
          IMPORT_LATEST_ONLY: ${{ inputs.import_latest_only == 'true' && '1' || '0' }}
          IMPORT_DEBUG: ${{ inputs.debug == 'true' && '1' || '0' }}
        run: |
          echo "=== python version ==="
          python --version
          echo "=== running importer ==="
          python scripts/rss_to_repo.py

      - name: Commit changes
        run: |
          set -euo pipefail
          echo "=== git status (before add) ==="
          git status
          git config user.name "Finch Bot"
          git config user.email "bot@fincharchive.com"
          git add _logs/** logs/** || echo "No _logs or logs to add"
          echo "=== git status (after add) ==="
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(logs): import new Substack posts & rebuild pages"
            git push origin main
          fi
