name: RSS → Repo (Substack sync)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser readability-lxml lxml html5lib html2text markdown jinja2

      - name: Run sync
        env:
          SUBSTACK_RSS_URL: "https://hallowayfinch.substack.com/feed"
          SITE_BASE_URL: "https://fincharchive.com"
        run: |
          python scripts/rss_to_repo.py

      - name: Commit changes
        run: |
          git config user.name "Finch Bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(logs): import new Substack posts & rebuild pages"
            git push
          fi
